version: '3.7'

services:

  frontend:
    container_name: react-app
    build: ./
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    stdin_open: true
    command: npm run dev
